POST http://127.0.0.1:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

  {
    "type": "HealthCheck",
    "description": "Test description",
    "date": "1986-07-09",
    "specialist": "Test Specialist",
    "diagnosisCodes": ["Z57.1"],
    "healthCheckRating": 2
  }




